// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NengaJouSimple.Data;

namespace NengaJouSimple.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210918141737_AddingAddressCardLayoutTable")]
    partial class AddingAddressCardLayoutTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.8");

            modelBuilder.Entity("NengaJouSimple.Models.Addresses.AddressCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address2")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFamilyPrinting")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPrintTarget")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MainName")
                        .HasColumnType("TEXT");

                    b.Property<string>("MainNameKana")
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PrintedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegisterdDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Renmei1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Renmei2")
                        .HasColumnType("TEXT");

                    b.Property<string>("Renmei3")
                        .HasColumnType("TEXT");

                    b.Property<string>("Renmei4")
                        .HasColumnType("TEXT");

                    b.Property<string>("Renmei5")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SenderAddressCardId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SenderAddressCardId");

                    b.ToTable("AddressCards");
                });

            modelBuilder.Entity("NengaJouSimple.Models.Addresses.SenderAddressCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address2")
                        .HasColumnType("TEXT");

                    b.Property<string>("MainName")
                        .HasColumnType("TEXT");

                    b.Property<string>("MainNameKana")
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegisterdDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Renmei1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Renmei2")
                        .HasColumnType("TEXT");

                    b.Property<string>("Renmei3")
                        .HasColumnType("TEXT");

                    b.Property<string>("Renmei4")
                        .HasColumnType("TEXT");

                    b.Property<string>("Renmei5")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SenderAddressCards");
                });

            modelBuilder.Entity("NengaJouSimple.Models.Layouts.AddressCardLayout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AddressCardId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegisterdDateTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AddressCardId");

                    b.ToTable("AddressCardLayouts");
                });

            modelBuilder.Entity("NengaJouSimple.Models.Addresses.AddressCard", b =>
                {
                    b.HasOne("NengaJouSimple.Models.Addresses.SenderAddressCard", "SenderAddressCard")
                        .WithMany()
                        .HasForeignKey("SenderAddressCardId");

                    b.Navigation("SenderAddressCard");
                });

            modelBuilder.Entity("NengaJouSimple.Models.Layouts.AddressCardLayout", b =>
                {
                    b.HasOne("NengaJouSimple.Models.Addresses.AddressCard", "AddressCard")
                        .WithMany()
                        .HasForeignKey("AddressCardId");

                    b.OwnsOne("NengaJouSimple.Models.Layouts.TextLayout", "Address", b1 =>
                        {
                            b1.Property<int>("AddressCardLayoutId")
                                .HasColumnType("INTEGER");

                            b1.Property<double>("FontSize")
                                .HasColumnType("REAL");

                            b1.Property<string>("Position")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Text")
                                .HasColumnType("TEXT");

                            b1.Property<int>("TextLayoutKind")
                                .HasColumnType("INTEGER");

                            b1.HasKey("AddressCardLayoutId");

                            b1.ToTable("AddressCardLayouts");

                            b1.WithOwner("AddressCardLayout")
                                .HasForeignKey("AddressCardLayoutId");

                            b1.Navigation("AddressCardLayout");
                        });

                    b.OwnsOne("NengaJouSimple.Models.Layouts.TextLayout", "Addressee", b1 =>
                        {
                            b1.Property<int>("AddressCardLayoutId")
                                .HasColumnType("INTEGER");

                            b1.Property<double>("FontSize")
                                .HasColumnType("REAL");

                            b1.Property<string>("Position")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Text")
                                .HasColumnType("TEXT");

                            b1.Property<int>("TextLayoutKind")
                                .HasColumnType("INTEGER");

                            b1.HasKey("AddressCardLayoutId");

                            b1.ToTable("AddressCardLayouts");

                            b1.WithOwner("AddressCardLayout")
                                .HasForeignKey("AddressCardLayoutId");

                            b1.Navigation("AddressCardLayout");
                        });

                    b.OwnsOne("NengaJouSimple.Models.Layouts.TextLayout", "PostalCode", b1 =>
                        {
                            b1.Property<int>("AddressCardLayoutId")
                                .HasColumnType("INTEGER");

                            b1.Property<double>("FontSize")
                                .HasColumnType("REAL");

                            b1.Property<string>("Position")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Text")
                                .HasColumnType("TEXT");

                            b1.Property<int>("TextLayoutKind")
                                .HasColumnType("INTEGER");

                            b1.HasKey("AddressCardLayoutId");

                            b1.ToTable("AddressCardLayouts");

                            b1.WithOwner("AddressCardLayout")
                                .HasForeignKey("AddressCardLayoutId");

                            b1.Navigation("AddressCardLayout");
                        });

                    b.OwnsOne("NengaJouSimple.Models.Layouts.TextLayout", "Sender", b1 =>
                        {
                            b1.Property<int>("AddressCardLayoutId")
                                .HasColumnType("INTEGER");

                            b1.Property<double>("FontSize")
                                .HasColumnType("REAL");

                            b1.Property<string>("Position")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Text")
                                .HasColumnType("TEXT");

                            b1.Property<int>("TextLayoutKind")
                                .HasColumnType("INTEGER");

                            b1.HasKey("AddressCardLayoutId");

                            b1.ToTable("AddressCardLayouts");

                            b1.WithOwner("AddressCardLayout")
                                .HasForeignKey("AddressCardLayoutId");

                            b1.Navigation("AddressCardLayout");
                        });

                    b.OwnsOne("NengaJouSimple.Models.Layouts.TextLayout", "SenderAddress", b1 =>
                        {
                            b1.Property<int>("AddressCardLayoutId")
                                .HasColumnType("INTEGER");

                            b1.Property<double>("FontSize")
                                .HasColumnType("REAL");

                            b1.Property<string>("Position")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Text")
                                .HasColumnType("TEXT");

                            b1.Property<int>("TextLayoutKind")
                                .HasColumnType("INTEGER");

                            b1.HasKey("AddressCardLayoutId");

                            b1.ToTable("AddressCardLayouts");

                            b1.WithOwner("AddressCardLayout")
                                .HasForeignKey("AddressCardLayoutId");

                            b1.Navigation("AddressCardLayout");
                        });

                    b.OwnsOne("NengaJouSimple.Models.Layouts.TextLayout", "SenderPostalCode", b1 =>
                        {
                            b1.Property<int>("AddressCardLayoutId")
                                .HasColumnType("INTEGER");

                            b1.Property<double>("FontSize")
                                .HasColumnType("REAL");

                            b1.Property<string>("Position")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Text")
                                .HasColumnType("TEXT");

                            b1.Property<int>("TextLayoutKind")
                                .HasColumnType("INTEGER");

                            b1.HasKey("AddressCardLayoutId");

                            b1.ToTable("AddressCardLayouts");

                            b1.WithOwner("AddressCardLayout")
                                .HasForeignKey("AddressCardLayoutId");

                            b1.Navigation("AddressCardLayout");
                        });

                    b.Navigation("Address");

                    b.Navigation("AddressCard");

                    b.Navigation("Addressee");

                    b.Navigation("PostalCode");

                    b.Navigation("Sender");

                    b.Navigation("SenderAddress");

                    b.Navigation("SenderPostalCode");
                });
#pragma warning restore 612, 618
        }
    }
}
